In [10]:
import pandas as pd

In [32]:
sentence = 'Do you like green eggs and ham?'

In [33]:
sentence.lower().strip('?').split()

['do', 'you', 'like', 'green', 'eggs', 'and', 'ham']

In [45]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

In [47]:
vectorizer.fit([sentence])

CountVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern=u'(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [48]:
vectorizer.get_feature_names()

[u'and', u'do', u'eggs', u'green', u'ham', u'like', u'you']

In [49]:
vectorizer.transform([sentence])

<1x7 sparse matrix of type '<type 'numpy.int64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [50]:
vectorizer.transform([sentence]).toarray()

array([[1, 1, 1, 1, 1, 1, 1]])

In [59]:
text = ['Do you like green eggs and ham?',
        'I do not like them, Sam-I-am.',
       'I do not like green eggs and ham.',
       'Not in a box. Not with a fox']

In [60]:
vectorizer.fit(text)

CountVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern=u'(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [61]:
vectorizer.get_feature_names()

[u'am',
 u'and',
 u'box',
 u'do',
 u'eggs',
 u'fox',
 u'green',
 u'ham',
 u'in',
 u'like',
 u'not',
 u'sam',
 u'them',
 u'with',
 u'you']

In [62]:
vectorizer.transform(text).toarray()

array([[0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1],
       [1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0],
       [0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 2, 0, 0, 1, 0]])

In [63]:
words = pd.DataFrame(vectorizer.transform(text).toarray(),
                    columns = vectorizer.get_feature_names())

In [64]:
words

am  and  box  do  eggs  fox  green  ham  in  like  not  sam  them  with  \
0   0    1    0   1     1    0      1    1   0     1    0    0     0     0   
1   1    0    0   1     0    0      0    0   0     1    1    1     1     0   
2   0    1    0   1     1    0      1    1   0     1    1    0     0     0   
3   0    0    1   0     0    1      0    0   1     0    2    0     0     1   

   you  
0    1  
1    0  
2    0  
3    0

In [65]:
words['text'] = text

In [66]:
words

am  and  box  do  eggs  fox  green  ham  in  like  not  sam  them  with  \
0   0    1    0   1     1    0      1    1   0     1    0    0     0     0   
1   1    0    0   1     0    0      0    0   0     1    1    1     1     0   
2   0    1    0   1     1    0      1    1   0     1    1    0     0     0   
3   0    0    1   0     0    1      0    0   1     0    2    0     0     1   

   you                               text  
0    1    Do you like green eggs and ham?  
1    0      I do not like them, Sam-I-am.  
2    0  I do not like green eggs and ham.  
3    0       Not in a box. Not with a fox

In [116]:
bigram_vectorizer = CountVectorizer(ngram_range=(1,2))


In [117]:
bigram_vectorizer.fit(text)

CountVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 2), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern=u'(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [118]:
bigram_vectorizer.get_feature_names()

[u'am',
 u'and',
 u'and ham',
 u'box',
 u'box not',
 u'do',
 u'do not',
 u'do you',
 u'eggs',
 u'eggs and',
 u'fox',
 u'green',
 u'green eggs',
 u'ham',
 u'in',
 u'in box',
 u'like',
 u'like green',
 u'like them',
 u'not',
 u'not in',
 u'not like',
 u'not with',
 u'sam',
 u'sam am',
 u'them',
 u'them sam',
 u'with',
 u'with fox',
 u'you',
 u'you like']

In [119]:
len(bigram_vectorizer.get_feature_names())

31

In [120]:
bigs = pd.DataFrame(bigram_vectorizer.transform(text).toarray(),
                    columns = bigram_vectorizer.get_feature_names())

In [121]:
bigs

am  and  and ham  box  box not  do  do not  do you  eggs  eggs and  \
0   0    1        1    0        0   1       0       1     1         1   
1   1    0        0    0        0   1       1       0     0         0   
2   0    1        1    0        0   1       1       0     1         1   
3   0    0        0    1        1   0       0       0     0         0   

     ...     not like  not with  sam  sam am  them  them sam  with  with fox  \
0    ...            0         0    0       0     0         0     0         0   
1    ...            1         0    1       1     1         1     0         0   
2    ...            1         0    0       0     0         0     0         0   
3    ...            0         1    0       0     0         0     1         1   

   you  you like  
0    1         1  
1    0         0  
2    0         0  
3    0         0  

[4 rows x 31 columns]

In [122]:
bigram_vectorizer.set_params(min_df = 2)

CountVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=2,
        ngram_range=(1, 2), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern=u'(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [123]:
bigram_vectorizer.fit(text)
len(bigram_vectorizer.get_feature_names())


13

In [124]:
bigs = pd.DataFrame(bigram_vectorizer.transform(text).toarray(),
                    columns = bigram_vectorizer.get_feature_names())
bigs

and  and ham  do  do not  eggs  eggs and  green  green eggs  ham  like  \
0    1        1   1       0     1         1      1           1    1     1   
1    0        0   1       1     0         0      0           0    0     1   
2    1        1   1       1     1         1      1           1    1     1   
3    0        0   0       0     0         0      0           0    0     0   

   like green  not  not like  
0           1    0         0  
1           0    1         1  
2           1    1         1  
3           0    2         0

In [67]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [68]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_vectorizer.fit(text)

TfidfVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm=u'l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern=u'(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [69]:
print(tfidf_vectorizer.transform(text).toarray())


[[ 0.    0.38  0.    0.31  0.38  0.    0.38  0.38  0.    0.31  0.    0.    0.
   0.    0.48]
 [ 0.49  0.    0.    0.31  0.    0.    0.    0.    0.    0.31  0.31  0.49
   0.49  0.    0.  ]
 [ 0.    0.41  0.    0.33  0.41  0.    0.41  0.41  0.    0.33  0.33  0.    0.
   0.    0.  ]
 [ 0.    0.    0.42  0.    0.    0.42  0.    0.    0.42  0.    0.54  0.    0.
   0.42  0.  ]]


In [9]:
tfidf_vectorizer.get_feature_names()

[u'end', u'fire', u'ice', u'in', u'say', u'some', u'the', u'will', u'world']

In [73]:
words = pd.DataFrame(tfidf_vectorizer.transform(text).toarray(),
                    columns = tfidf_vectorizer.get_feature_names())
words['text'] = text

In [83]:
tfidf_vectorizer = TfidfVectorizer(min_df = 2,
                                   max_df = .9)

In [84]:
tfidf_vectorizer.fit(text)

words = pd.DataFrame(tfidf_vectorizer.transform(text).toarray(),
                    columns = tfidf_vectorizer.get_feature_names())
words['text'] = text
words

and        do      eggs     green       ham      like       not  \
0  0.433928  0.351302  0.433928  0.433928  0.433928  0.351302  0.000000   
1  0.000000  0.577350  0.000000  0.000000  0.000000  0.577350  0.577350   
2  0.409400  0.331445  0.409400  0.409400  0.409400  0.331445  0.331445   
3  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  1.000000   

                                text  
0    Do you like green eggs and ham?  
1      I do not like them, Sam-I-am.  
2  I do not like green eggs and ham.  
3       Not in a box. Not with a fox

In [85]:
tfidf_vectorizer.set_params(stop_words = 'english')

tfidf_vectorizer.fit(text)

words = pd.DataFrame(tfidf_vectorizer.transform(text).toarray(),
                    columns = tfidf_vectorizer.get_feature_names())
words['text'] = text
words

eggs     green       ham      like                               text
0  0.523035  0.523035  0.523035  0.423442    Do you like green eggs and ham?
1  0.000000  0.000000  0.000000  1.000000      I do not like them, Sam-I-am.
2  0.523035  0.523035  0.523035  0.423442  I do not like green eggs and ham.
3  0.000000  0.000000  0.000000  0.000000       Not in a box. Not with a fox

In [90]:
from nltk.stem import SnowballStemmer

stemmer = SnowballStemmer("english")

In [98]:
from string import punctuation

def quick_stemmer(sentence):
    s = sentence.lower()
    s = s.split()
    s = [w.strip(punctuation) for w in s]
    s = [stemmer.stem(w) for w in s]
    return ' '.join(s)

u'not in a box not with a fox'

In [99]:
quick_stemmer("Man trapped in Texas cash machine sends 'help me' notes")

u'man trap in texa cash machin send help me note'

In [101]:
words['stemmed'] = words['text'].apply(quick_stemmer)

In [102]:
words

eggs     green       ham      like                               text  \
0  0.523035  0.523035  0.523035  0.423442    Do you like green eggs and ham?   
1  0.000000  0.000000  0.000000  1.000000      I do not like them, Sam-I-am.   
2  0.523035  0.523035  0.523035  0.423442  I do not like green eggs and ham.   
3  0.000000  0.000000  0.000000  0.000000       Not in a box. Not with a fox   

                           stemmed  
0    do you like green egg and ham  
1      i do not like them sam-i-am  
2  i do not like green egg and ham  
3      not in a box not with a fox

In [125]:
from sklearn.datasets import fetch_20newsgroups



In [128]:
categories = ['alt.atheism', 
              'talk.religion.misc', 
              ]

newsgroups = fetch_20newsgroups(categories=categories)



In [130]:
newsgroups.target_names

['alt.atheism', 'talk.religion.misc']

In [131]:
newsgroups.target[:10]

array([0, 0, 0, 1, 1, 0, 0, 1, 0, 0])

In [134]:
target_names = [newsgroups.target_names[i] for i in newsgroups.target]
target_names[:10]

['alt.atheism',
 'alt.atheism',
 'alt.atheism',
 'talk.religion.misc',
 'talk.religion.misc',
 'alt.atheism',
 'alt.atheism',
 'talk.religion.misc',
 'alt.atheism',
 'alt.atheism']

In [135]:
newsgroups.data[5]

u' howland.reston.ans.net!europa.eng.gtefsd.com!uunet!mcsun!Germany.EU.net!news.dfn.de!tubsibr!dbstu1.rz.tu-bs.de!I3150101\nSubject: Re: Gospel Dating\nFrom: I3150101@dbstu1.rz.tu-bs.de (Benedikt Rosenau)\nOrganization: Technical University Braunschweig, Germany\nLines: 35\n\nIn article <66015@mimsy.umd.edu>\nmangoe@cs.umd.edu (Charley Wingate) writes:\n \n(Deletion)\n>I cannot see any evidence for the V. B. which the cynics in this group would\n>ever accept.  As for the second, it is the foundation of the religion.\n>Anyone who claims to have seen the risen Jesus (back in the 40 day period)\n>is a believer, and therefore is discounted by those in this group; since\n>these are all ancients anyway, one again to choose to dismiss the whole\n>thing.  The third is as much a metaphysical relationship as anything else--\n>even those who agree to it have argued at length over what it *means*, so\n>again I don\'t see how evidence is possible.\n>\n \nNo cookies, Charlie. The claims that Jesus h

In [139]:
print(newsgroups.data[5])

 howland.reston.ans.net!europa.eng.gtefsd.com!uunet!mcsun!Germany.EU.net!news.dfn.de!tubsibr!dbstu1.rz.tu-bs.de!I3150101
Subject: Re: Gospel Dating
From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Rosenau)
Organization: Technical University Braunschweig, Germany
Lines: 35

In article <66015@mimsy.umd.edu>
mangoe@cs.umd.edu (Charley Wingate) writes:
 
(Deletion)
>I cannot see any evidence for the V. B. which the cynics in this group would
>ever accept.  As for the second, it is the foundation of the religion.
>Anyone who claims to have seen the risen Jesus (back in the 40 day period)
>is a believer, and therefore is discounted by those in this group; since
>these are all ancients anyway, one again to choose to dismiss the whole
>thing.  The third is as much a metaphysical relationship as anything else--
>even those who agree to it have argued at length over what it *means*, so
>again I don't see how evidence is possible.
>
 
No cookies, Charlie. The claims that Jesus have been seen are discr

In [141]:
df = pd.DataFrame(zip(target_names, newsgroups.data),
                  columns = ['newsgroup','text'] )

In [142]:
df.head()

newsgroup                                               text
0         alt.atheism  From: mangoe@cs.umd.edu (Charley Wingate)\nSub...
1         alt.atheism  Subject: Re: There must be a creator! (Maybe)\...
2         alt.atheism  From: MANDTBACKA@FINABO.ABO.FI (Mats Andtbacka...
3  talk.religion.misc  From: royc@rbdc.wsnc.org (Roy Crabtree)\nSubje...
4  talk.religion.misc  Subject: Re: "Imaginary" Friends - Info and Ex...

In [143]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer()
X_counts = count_vect.fit_transform(df['text'])

In [144]:
from sklearn.naive_bayes import MultinomialNB